export const HOME_PAGE_BASE_URL = 'https://wallpaperscraft.com/all/';
export const CATEGORY_BASE_URL = 'https://wallpaperscraft.com/catalog/';
export const DOWNLOAD_BASE_URL = 'https://images.wallpaperscraft.com/';

export const RESOLUTION_PIXELS = {
  2160: '2160x3840',
  1440: '1440x2560',
  1366: '1366x768',
  1080: '1080x1920',
  1024: '1024x600',
  960: '960x544',
  800: '800x600',
  720: '720x1280',
  540: '540x960',
  480: '480x854',
  480: '480x800',
  360: '360x640',
  320: '320x480',
  320: '320x240',
  240: '240x400',
  240: '240x320',
};

export const COLOR_SCHEME = {
  primaryTextColor: '#15024f',
  secondaryTextColor: '#919191',
  primaryBackgroundColor: '#fff',
  secondaryBackgroundColor: '#e8e8e8',
};

export const TAB_ICONS = {
  home: 'wallpaper',
  category: 'compass',
  downloads: 'download-circle',
  profile: 'face-profile',
};

export const CATEGORIES = {
  '3d': '3d',
  abstract: 'abstract',
  animals: 'animals',
  anime: 'anime',
  art: 'art',
  black: 'black',
  cars: 'cars',
  city: 'city',
  dark: 'dark',
  fantasy: 'fantasy',
  flowers: 'flowers',
  food: 'food',
  holidays: 'holidays',
  love: 'love',
  macro: 'macro',
  minimalism: 'minimalism',
  motorcycles: 'motorcycles',
  music: 'music',
  nature: 'nature',
  other: 'other',
  smilies: 'smilies',
  space: 'space',
  sport: 'sport',
  'hi-tech': 'hi-tech',
  textures: 'textures',
  vector: 'vector',
  words: 'words',
};
export const CATEGORY_LIST = [
  '3d',
  'abstract',
  'animals',
  'anime',
  'art',
  'black',
  'cars',
  'city',
  'dark',
  'fantasy',
  'flowers',
  'food',
  'holidays',
  'love',
  'macro',
  'minimalism',
  'motorcycles',
  'music',
  'nature',
  'other',
  'smilies',
  'space',
  'sport',
  'hi-tech',
  'textures',
  'vector',
  'words',
];
