export const API_NAME = {
  LOGIN: 'auth/login',
  SIGNUP: 'auth',
  USER_DATA: 'auth/data',
  UPDATE_USER: 'auth/update',
  CHANGE_PASSWORD: 'auth/reset',
  COURSES: 'courses/allCourses',
  BUY_NEW_COURSES: 'courses/',
  MY_COURSES: 'courses/myCourses',
  MY_COURSE_IDS: 'courses/oneCourse',
  VIDEOS: 'videos/fetch',
  LIBRARY: 'library/fetch',
  IMAGES: 'images/',
  CATEGORY: 'category',
  FEATURED: 'courses/featured/category',
};
